apiVersion: cert-manager.io/v1
 
kind: Certificate
metadata:
  name: multik8s-net-tls
spec:
  secretName: multik8s-net
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: multi-k8s.net
  dnsNames:
    - multi-k8s.net
    - www.multi-k8s.net